/**
 * knacks App
 * @author: Schemaphic Systems
 */

//event names

//loader related events
export const SHOW_PRELOADER = "SHOW_PRELOADER";
export const HIDE_PRELOADER = "HIDE_PRELOADER";

export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const SHOW_MENU_FROM_BOTTOM = "SHOW_MENU_FROM_BOTTOM";
export const HIDE_MENU_FROM_BOTTOM = "HIDE_MENU_FROM_BOTTOM";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const ACTION_NOTIFICATION = "ACTION_NOTIFICATION";
export const SEND_REMOTE_NOTIFY = "SEND_REMOTE_NOTIFY";
export const REMOVE_NOTIFICATION_COUNT = "REMOVE_NOTIFICATION_COUNT";
export const UPDATE_NOTIFICATION_BADGE_COUNT = "UPDATE_NOTIFICATION_BADGE_COUNT";
export const FETCH_NOTIFICATION_BADGE_COUNT = "FETCH_NOTIFICATION_BADGE_COUNT";
export const WITHOUT_ACTION_NOTIFICATION = "WITHOUT_ACTION_NOTIFICATION";
export const REMOVE_KNACKER_IN_CHAT = "REMOVE_KNACKER_IN_CHAT";

//Login related events
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const FORCE_LOGOUT = "FORCE_LOGOUT";